name: CI
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - uses: golangci/golangci-lint-action@c67416616c29c3c48d26b59c45cadb56966d80aa
        with:
          args: --timeout=5m
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - run: go test -v ./...
  release:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - uses: sumanchapai/go-semantic-release-action@v1
        with:
          pre-release-post-dry-cmd: "cp .version cmd/.version"
          files-to-commit: "cmd/.version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
